spring:
  main: 
    banner-mode: off
hibernate:
  hbm2ddl: 
    auto: validate
---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tracker
    user: admin
    password: 
    